### ISSUE TITLE
Hard to install obspy 1.1.1 with dependency on old proj4

### ISSUE THREAD

**Issue by mhearne-usgs** [conda-forge/obspy-feedstock#27] opened 2019-08-01 13:14 UTC
Issue:
One of the conda-forge maintainers had to go back and build an older version of proj4 in the conda-forge ecosystem so that I can hopefully link against it with my package. He says this dependency on an older version makes it difficult to use with other packages that have upgraded to newer versions. Is it possible to change that dependency?
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by megies** [comment] 2019-08-01 14:11
@mhearne-usgs if I remember correctly, the only reason for that pinning was the problem described here: matplotlib/basemap#443

You could help by researching which proj4 versions are safe and which have the problem, rebuilding our conda packages should be trivial if we know how to change the pinning rules.

**Comment by ocefpaf** [comment] 2019-08-01 14:50
@megies I don't think that is productive. `obspy` should move away from `basemap`. Basemap is defunct and bugfix support will end in 2020. See https://matplotlib.org/basemap/users/intro.html#cartopy-new-management-and-eol-announcement

**Comment by megies** [comment] 2019-08-01 14:57
Users can already chose to use cartopy with obspy instead. We don't have basemap as a hard dependency either. Just sayin, the pinning could be changed in the blink of an eye.

**Comment by ocefpaf** [comment] 2019-08-01 15:16
> Users can already chose to use cartopy with obspy instead. We don't have basemap as a hard dependency either. 

Then the conda-forge package should be fixed by removing the `basenmap` dependency. Even better would be if two other meta-pacakges obspy-basemap and obspy-cartopy would be created to make it easier to install the optional dependencies.

> Just sayin, the pinning could be changed in the blink of an eye.

That is up to the maintainers of the package.

**Comment by ThomasLecocq** [comment] 2019-08-01 15:27
I think we can close this discussion now, before it gets too wild.

**Comment by ocefpaf** [comment] 2019-08-01 15:32
> I think we can close this discussion now, before it gets too wild.

Why? The issue is not resolved.

What do you mean by wild? Everything so far was to the point regarding fixing the issue. The solution is a PR to remove `basemap` and preferably adding `cartopy` or creating the meta-packages too.

**Comment by ThomasLecocq** [comment] 2019-08-01 15:38
Oh yes ok, so please provide this PR so we can work on it for 1.2.0.

**Comment by ocefpaf** [comment] 2019-08-01 15:52
> Oh yes ok, so please provide this PR so we can work on it for 1.2.0.

Whenever I have some free time I can sure help the maintainers, @megies, @krischer, @barsch, @QuLogic or @ThomasLecocq, to address this.

**Comment by megies** [comment] 2019-08-02 08:50
> two other meta-pacakges obspy-basemap and obspy-cartopy would be created to make it easier to install the optional dependencies

You'd be surprised how much installation problem questions we get when it is just one line to install obspy with Anaconda in principal. If we make obspy not depend on basemap, we'll get flooded with github tickets "I installed obspy but the station map plots are not working".
I agree this might make sense, but to be honest, I'd actually much prefer how `apt` is handling this, by means of `Recommends:` section and `|` or operator (will get installed if possible, else left out, offering multiple solutions to the dependency resolution). But I know the conda dependency resolution is a beast already and has to handle zillions more possible combinations of dependency versions, so I'll not bring it up there.

**Comment by megies** [comment] 2020-03-19 09:54
Closed by #38

**Closed as completed by megies** 2020-03-19 09:54 UTC
